[package]
name = "vm"
version = "0.1.0"
authors = []

[lib]
name = "vm"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
redis = "0.8.0"
rustler = { git = "https://github.com/hansihe/rustler.git"}
rustler_codegen = "0.16.0"
lazy_static = "0.2"
wasmi = { git = "https://github.com/pepyakin/wasmi.git" }
serde_cbor = "0.8.2"
rocksdb = "0.9.1"
